### ISSUE TITLE
feat: Add html display to get request

### ISSUE THREAD

**Issue by richod1** [codekeyz/pharaoh#106]
**Description**

Clearly describe what you are looking to add. The more context the better.
In express one can send HTML elements in response eg:app.get("/",(req,res)=>res.ok("<h1>Hello World</h1>"));

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by codekeyz** [comment]
@richod1 You can send html response but you will use the `res.send` function. 

`res.ok` will send whatever you provide as `text/plain`
