### ISSUE TITLE
feat: Be able to test whole URIs

### ISSUE THREAD

**Issue by jxstxn1** [codekeyz/pharaoh#110]
**Description**

I would like to have a way to define a base URI of the server in a Spookie Test.
Similar to the `uri` Parameter in the `Request` Object in shelf

**Requirements**

- [x] Add a way to add a base URI to a request in Spookie

**Comment by codekeyz** [comment]
@jxstxn1 This should make that possible https://github.com/codekeyz/pharaoh/pull/111
