### ISSUE TITLE
perf: router wastes most of its runtime on creating debug strings which are not used in production

### ISSUE THREAD

**Issue by helightdev** [codekeyz/pharaoh#128]
The spanner router wastes most of its runtime on creating debug strings which are not used in production.

## Explanation
![Screenshot from 2024-06-11 19-38-14](https://github.com/codekeyz/pharaoh/assets/38019186/2608ef39-22b5-4ad8-a196-4b736b25dd60)

As you can see here, the strings are always created even if the devlog is not printed. Besides this unneccesary string concatenation happening there, the equatable package used for the nodes makes this even slower since it is inherrently inperformant.

You can see this in the dart observatory output:
![image](https://github.com/codekeyz/pharaoh/assets/38019186/c58de94f-320d-426f-9e5f-eafe91832607)

If you look at the Spanner specific benchmark I was testing, you can see how most of the time is spent either in the EquatableMixin, String concation and other debug related stuff.

## Fixing this
- Just make the debug method use a function instead of finished strings (Still not optimal)
- Put the stuff in assert trap lambas ("In production code, assertions are ignored, and the arguments to assert aren’t evaluated.")
```dart
  assert(() {
    //you can execute debug-specific codes here
    return true;
  }());
```
- Just remove them
- Add a second tree that has debug output

**Comment by codekeyz** [comment]
@helightdev Nice catch. Could you submit a PR to put the debug logs behind the assertion?

**Comment by codekeyz** [comment]
@helightdev Could you provide a repo to this benchmark? I've never really had time to do in-depth benchmark on Spanner. Prolly worth dedicating a weekend to nailing perf issues.

**Comment by helightdev** [comment]
https://github.com/helightdev/shelf_openrouter/tree/main/benchmark

**Comment by codekeyz** [comment]
Thanks alot @helightdev
