### ISSUE TITLE
join efforts in developing the angel framework 

### ISSUE THREAD

**Issue by insinfo** [codekeyz/pharaoh#55]
@codekeyz @iamEtornam @rasheedmhd @dukefirehawk
Although I admire your dedication to creating another framework, I think that instead of creating another framework we could join efforts in developing the angel framework here
https://github.com/dukefirehawk/angel

**Comment by codekeyz** [comment]
@insinfo I nearly almost took that route. But i realized it's wasn't gonna be worth it considering what i wanted to build. Angel and these other frameworks are more like the NestJS and AdonisJS of Dart. While that might sound nice and dandy, that comes with a-lot to maintain as part of the framework by a relatively small group of adopters considering Dart is still not a popular choice for backend.

Pharaoh is completely different in the sense that we're building almost a replica of ExpressJS but for Dart. It's lightweight and works for your basic needs. Almost like what the Dart team wanted to achieve with Shelf (but i have issues with their paradigm). 

I want something that people can try easily without all the fuss and an interface that doesn't require alot to process. Then they can create their own packages to keep the framework afloat. That's how you make a framework grow without unnecessary overhead.

I look at those these other code-bases and I feel overly overwhelmed.
